// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ooonvkmulgsgkrczkmti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vb252a211bGdzZ2tyY3prbXRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4Njc2NzEsImV4cCI6MjA1MjQ0MzY3MX0.m5V1b8VkQdzRbPeF7ifbfsTix81QRQtLKSPS0Rrb__M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);